spring.application.name=hospital.management

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management 
#jdbc - Java Database Connectivity, postgresql - database type, localhost - host name, 5432 - port number, hospital_management - database name
spring.datasource.username=postgres
#user account for the database, by default, the username is postgres
spring.datasource.password=postgresql123

spring.jpa.hibernate.ddl-auto=update
# it is used to automatically create the database tables based on the entity classes. The value "update" means 
# that Hibernate will update the existing tables to match the entity classes,and also create new ones if needed.
spring.jpa.show-sql=true
#This prints SQL statements in the console.
spring.jpa.properties.hibernate.format_sql=true
#This formats the SQL statements printed in the console for better readability.